apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-backup
spec:
  kafka:
    resources:
      requests:
        memory: 500Mi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: "1"
    jvmOptions:
      -Xms: 1024m
      -Xmx: 1024m
    version: 3.9.0
    replicas: 1
    template:
      pod:
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "backup"
            effect: "NoSchedule"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: mirroring
        port: 9093
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.9"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    template:
      pod:
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "backup"
            effect: "NoSchedule"
    resources:
      requests:
        memory: 250Mi
        cpu: 250m
      limits:
        memory: 500Mi
        cpu: 500m
    jvmOptions:
      -Xms: 512m
      -Xmx: 512m
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
