apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: streams-cluster
spec:
  kafka:
    resources:
      requests:
        memory: 500Mi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: "1"
    jvmOptions:
      -Xms: 1024m
      -Xmx: 1024m
    version: 3.9.0
    replicas: 3
    rack:
      topologyKey: topology.kubernetes.io/zone
    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: strimzi.io/name
                      operator: In
                      values:
                        - streams-cluster-kafka
                topologyKey: topology.kubernetes.io/zone
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: mirroring
        port: 9093
        type: ingress
        tls: true
        configuration:
          bootstrap:
            host: bootstrap.$INGRESS_NGINX_IP.nip.io
          brokers:
          - broker: 0
            host: broker-0.$INGRESS_NGINX_IP.nip.io
          - broker: 1
            host: broker-1.$INGRESS_NGINX_IP.nip.io
          - broker: 2
            host: broker-2.$INGRESS_NGINX_IP.nip.io
        authentication:
          type: tls
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.9"
      # Disable auto creation of topic on the server
      auto.create.topics.enable: false
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 2Gi
        deleteClaim: false
  zookeeper:
    replicas: 3
    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: strimzi.io/name
                      operator: In
                      values:
                        - streams-cluster-zookeeper
                topologyKey: topology.kubernetes.io/zone
    resources:
      requests:
        memory: 250Mi
        cpu: 250m
      limits:
        memory: 500Mi
        cpu: 500m
    jvmOptions:
      -Xms: 512m
      -Xmx: 512m
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
