apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: mirroring-user
  labels:
    strimzi.io/cluster: streams-cluster
spec:
  authentication:
    type: tls
  # super-users do not declare authorization block  
