apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: primary-mirroring-user
  labels:
    strimzi.io/cluster: streams-cluster
spec:
  authentication:
    type: scram-sha-512
  # super-users do not declare authorization block