apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: mirroring-user
  labels:
    strimzi.io/cluster: streams-cluster
spec:
  authentication:
    type: scram-sha-512  
  # The mirroring user needs only read and describe permissions 
  # if mm2 is configured to create is mm2-offset-syncs topic into the target cluster 
  # and not into the source cluster (that's the default behaviour)
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operations:
          - Read
          - DescribeConfigs
        host: "*"
      - resource:
          type: group
          name: "*"
          patternType: literal
        operations:
          - Read
          - Describe
        host: "*"
      - resource:
          type: cluster
          patternType: literal
        operations:
          - Describe
        host: "*"
  # In order to protect the source cluster, we could insert user quotas for network traffic
  # quotas:
  #   consumerByteRate: 52428800 # 50MiB/s per broker
  #   producerByteRate: 52428800 # 50MiB/s per broker
  #   requestPercentage: 50