apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: writer-user
  labels:
    strimzi.io/cluster: streams-cluster
spec:
  authentication:
    type: scram-sha-512
  # Producer ACLs for topic my-topic
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "my-topic"
          patternType: literal
        operations:
          - Write
          - Describe
        host: "*"